"""SQL translation for the Postgres storage path.

These run everywhere. The end-to-end run against a real Postgres lives in
test_postgres_live.py.
"""

from __future__ import annotations

from app.storage import db, pg


def test_placeholders_and_percent_signs_are_translated_outside_quotes():
    text, returns_id = pg.translate("SELECT * FROM entries WHERE athlete_id LIKE ? AND note = 'a?%'")
    assert text == "SELECT * FROM entries WHERE athlete_id LIKE %s AND note = 'a?%%'"
    assert returns_id is False


def test_sqlite_ddl_becomes_postgres_ddl():
    text, _ = pg.translate("CREATE TABLE IF NOT EXISTS t (\n id INTEGER PRIMARY KEY AUTOINCREMENT,\n rpe REAL)")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in text
    assert "rpe DOUBLE PRECISION" in text
    assert pg.translate("PRAGMA journal_mode = WAL") == (None, False)
    column_query, _ = pg.translate("PRAGMA table_info(entries)")
    assert "information_schema.columns" in column_query and "'entries'" in column_query


def test_insert_or_ignore_and_generated_ids():
    tables = pg.identity_tables(db.SCHEMA)
    assert {"entries", "agent_cases", "agent_events", "plan_sessions"} <= tables
    assert "coach_channel" not in tables and "agent_lease" not in tables
    text, returns_id = pg.translate(
        "INSERT OR IGNORE INTO outbound_drafts (a) VALUES (?)", returning_tables=tables
    )
    assert text == "INSERT INTO outbound_drafts (a) VALUES (%s) ON CONFLICT DO NOTHING"
    assert not returns_id, "outbound_drafts is keyed by athlete, kind and date, not a generated id"
    text, returns_id = pg.translate("INSERT INTO entries (a) VALUES (?)", returning_tables=tables)
    assert text == "INSERT INTO entries (a) VALUES (%s) RETURNING id"
    assert returns_id
    text, returns_id = pg.translate(
        "INSERT INTO agent_lease (name) VALUES (?) ON CONFLICT (name) DO NOTHING", returning_tables=tables
    )
    assert not returns_id and not text.endswith("RETURNING id")


def test_every_schema_statement_translates():
    statements = pg.split_script(db.SCHEMA)
    assert len(statements) > 20
    for statement in statements:
        text, _ = pg.translate(statement)
        assert text is not None
        assert "AUTOINCREMENT" not in text and " REAL" not in text


def test_rows_behave_like_sqlite_rows():
    row = pg.Row(["id", "name"], [7, "Priya"])
    assert row["name"] == "Priya" and row[0] == 7 and dict(row) == {"id": 7, "name": "Priya"}
    assert pg._params([True, False, 3]) == (1, 0, 3)
