"""Postgres behind the same small connection interface the SQLite code uses.

The storage layer is written against sqlite3: `?` placeholders, rows indexed by
name, `cur.lastrowid`, `executescript` and `PRAGMA table_info`. Durable hosted
storage (Neon's free Postgres) needs none of that code rewritten; this module
translates the handful of SQLite-only forms the schema and queries use:

    ?                                  -> %s
    INTEGER PRIMARY KEY AUTOINCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    REAL                               -> DOUBLE PRECISION
    INSERT OR IGNORE INTO ...          -> INSERT INTO ... ON CONFLICT DO NOTHING
    PRAGMA table_info(t)               -> information_schema.columns
    cur.lastrowid                      -> INSERT ... RETURNING id

Anything else is passed through unchanged, so a new SQLite-only construct fails
loudly in the Postgres test rather than silently doing something different.
"""

from __future__ import annotations

import re
from typing import Any, Iterable, Iterator, Sequence

_PRAGMA_TABLE_INFO = re.compile(r"^\s*PRAGMA\s+table_info\((\w+)\)\s*$", re.I)
_PRAGMA_OTHER = re.compile(r"^\s*PRAGMA\b", re.I)
_INSERT_OR_IGNORE = re.compile(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", re.I)
_INSERT_INTO = re.compile(r"^\s*INSERT\s+INTO\s+(\w+)", re.I)
_AUTOINCREMENT = re.compile(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", re.I)
_REAL = re.compile(r"\bREAL\b")
_IDENTITY_TABLE = re.compile(
    r"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+(\w+)\s*\(\s*id\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
    re.I,
)

_ready_urls: set[str] = set()


def identity_tables(schema: str) -> frozenset[str]:
    """Tables whose inserts should report the generated id."""
    return frozenset(match.group(1).lower() for match in _IDENTITY_TABLE.finditer(schema))


def _placeholders(sql: str) -> str:
    """Swap `?` for `%s` and escape literal `%`, leaving quoted text alone."""
    out: list[str] = []
    quoted = False
    for char in sql:
        if char == "'":
            quoted = not quoted
            out.append(char)
        elif quoted:
            out.append("%%" if char == "%" else char)
        elif char == "?":
            out.append("%s")
        elif char == "%":
            out.append("%%")
        else:
            out.append(char)
    return "".join(out)


def translate(sql: str, *, returning_tables: frozenset[str] = frozenset()) -> tuple[str | None, bool]:
    """Postgres text for one SQLite statement, and whether it returns a new id.

    Returns (None, False) for SQLite settings with no Postgres meaning.
    """
    pragma = _PRAGMA_TABLE_INFO.match(sql)
    if pragma:
        return (
            "SELECT column_name AS name FROM information_schema.columns "
            f"WHERE table_schema = current_schema() AND table_name = '{pragma.group(1).lower()}'",
            False,
        )
    if _PRAGMA_OTHER.match(sql):
        return None, False

    text = _AUTOINCREMENT.sub("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql)
    text = _REAL.sub("DOUBLE PRECISION", text)
    ignore = bool(_INSERT_OR_IGNORE.search(text))
    if ignore:
        text = _INSERT_OR_IGNORE.sub("INSERT INTO", text)
    text = text.rstrip().rstrip(";")
    if ignore:
        text += " ON CONFLICT DO NOTHING"
    insert = _INSERT_INTO.match(text)
    returns_id = bool(
        insert and insert.group(1).lower() in returning_tables and not re.search(r"\bRETURNING\b", text, re.I)
    )
    if returns_id:
        text += " RETURNING id"
    return _placeholders(text), returns_id


def split_script(script: str) -> list[str]:
    statements = []
    for chunk in script.split(";"):
        lines = [line for line in chunk.splitlines() if not line.strip().startswith("--")]
        statement = "\n".join(lines).strip()
        if statement:
            statements.append(statement)
    return statements


class Row:
    """Indexable by column name or position, and convertible with dict(row)."""

    __slots__ = ("_names", "_values")

    def __init__(self, names: Sequence[str], values: Sequence[Any]):
        self._names = tuple(names)
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, (int, slice)):
            return self._values[key]
        try:
            return self._values[self._names.index(key)]
        except ValueError:
            raise IndexError(f"No item with that key: {key!r}") from None

    def keys(self) -> list[str]:
        return list(self._names)

    def __iter__(self) -> Iterator[Any]:
        return iter(self._values)

    def __len__(self) -> int:
        return len(self._values)


def _params(params: Iterable[Any] | None) -> tuple[Any, ...]:
    # SQLite stores booleans in INTEGER columns; Postgres needs them as integers too.
    return tuple(int(value) if isinstance(value, bool) else value for value in (params or ()))


class Cursor:
    def __init__(self, raw, returns_id: bool):
        self._raw = raw
        self.lastrowid = None
        self.rowcount = raw.rowcount if raw is not None else 0
        self._buffer: list[Row] | None = None
        if raw is not None and raw.description is not None:
            names = [column.name for column in raw.description]
            rows = [Row(names, values) for values in raw.fetchall()]
            if returns_id:
                self.lastrowid = rows[0]["id"] if rows else None
                self._buffer = []
            else:
                self._buffer = rows
        else:
            self._buffer = []

    def fetchone(self):
        return self._buffer.pop(0) if self._buffer else None

    def fetchall(self) -> list[Row]:
        rows, self._buffer = self._buffer, []
        return rows

    def __iter__(self) -> Iterator[Row]:
        return iter(self.fetchall())


class PostgresConnection:
    """The subset of sqlite3.Connection the storage layer relies on."""

    def __init__(self, raw, url: str, returning_tables: frozenset[str]):
        self._raw = raw
        self._url = url
        self._returning = returning_tables
        self.row_factory = None

    @property
    def schema_ready(self) -> bool:
        return self._url in _ready_urls

    def mark_schema_ready(self) -> None:
        _ready_urls.add(self._url)

    def execute(self, sql: str, params: Iterable[Any] | None = None) -> Cursor:
        text, returns_id = translate(sql, returning_tables=self._returning)
        if text is None:
            return Cursor(None, False)
        raw = self._raw.cursor()
        raw.execute(text, _params(params))
        return Cursor(raw, returns_id)

    def executescript(self, script: str) -> None:
        for statement in split_script(script):
            self.execute(statement)
        self.commit()

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


def connect_postgres(url: str, schema: str) -> PostgresConnection:
    try:
        import psycopg
    except ImportError as exc:  # pragma: no cover - depends on the deployment
        raise RuntimeError(
            "DATABASE_URL is set but psycopg is not installed; run pip install -r requirements.txt"
        ) from exc
    raw = psycopg.connect(url, connect_timeout=15)
    return PostgresConnection(raw, url, identity_tables(schema))
